### ISSUE TITLE
Shooting button stuck when Wacom tablet is connected, on Linux with 0.7.2

### ISSUE THREAD

**Issue by grepwood** [deathkiller/jazz2#67] opened 2022-01-31 16:47 UTC
Whenever my Wacom graphic tables is connected, the character will keep on shooting to no end.

OS: Linux
Jazz2 version: 0.7.2

**Comment by deathkiller** [comment] 2022-01-31 20:59
Is it possible it acts as gamepad? Shooting is mapped on right trigger.

**Comment by grepwood** [comment] 2022-02-01 12:51
It gets detected as a controller by the game, which is correct. It's essentially a USB interfaced pointing device (mouse) with the extra features of having extra buttons for graphic editing, and button press sensitivity - the mat of the tablet has different scale of sensitivity. My Wacom Intuos S has 4096 levels of sensitivity and this is used by graphic editing software like Gimp or Krita to determine how hard should a brush be pressed against the canvas. Additionally, the mat's 2D geometry is scaled to the 2D geometry of the total logical graphic display so that the tablet can tell the computer what part of the screen receives the input, i.e. the X-axis middle of the mat will correspond to the middle of a single screen setup, but it will correspond to the mid-section of a two screen setup, etc. So, if you really really want to, you can use a graphic tablet as a mouse if you lack one.

By default, having the tablet connected to the computer but left alone and uninteracted, shouldn't yield this kind of response from any software.

**Comment by deathkiller** [comment] 2022-02-01 12:56
Actions on triggers are hard-coded because triggers cannot be used in control remapping. So I will add switch to turn off these hard-coded actions probably.

**Comment by grepwood** [comment] 2022-02-01 13:04
Please be careful not to break actual gamepad/joystick support when limiting support for tablets. I'm eager to test.

**Comment by deathkiller** [comment] 2022-02-01 13:15
Before I make the changes, can you try to go to Controls settings and press Delete key on every assigned gamepad button? Then check if the problem persists.

**Comment by coreybruce** [comment] 2022-07-05 09:40
Having the same problem when my Xbox one controller is connect via Bluetooth on Linux

**Comment by dragon99919** [comment] 2022-07-21 11:47
Can confirm the second case as well - using Steam Deck here (and Steam Input), and whenever game starts, character starts shooting until I press the trigger manually, then it stops. Happens with both Xbox One controller and Steam Deck build-in controller. Also, no idea if that's a case for a buddy here above, but does your character always auto-run as well? I cannot seem to walk normally, and I tried pressing 'B' button on both controllers - no change whatsoever.

**Comment by deathkiller** [comment] 2022-07-21 12:24
Run is on the left trigger, maybe it can be related.

I'm going to rewrite Jazz² Resurrection to C++, it should have better performance and more supported platforms and devices, so it doesn't make much sense to fix anything here now. As a workaround you can unmap gamepad in Controls settings using Delete key.

**Comment by deathkiller** [comment] 2022-09-04 09:27
This should be fixed in new C++ version, so this will not be resolved in this C# version.

**Closed by deathkiller** 2022-09-04 09:27 UTC

**Comment by coreybruce** [comment] 2022-09-04 15:44
Confirmed not fixed on the latest [0.7.3](https://github.com/deathkiller/jazz2/releases/tag/0.7.3) 

it still does it also there is another controller bug which I will report to do with it getting the incorrect input from a xbox one controller that I will report .

**Comment by deathkiller** [comment] 2022-09-04 15:56
Yes, as I said, it will not be fixed here (because I can't fix it anyway, it's a bug in 3rd-party library), it should be already fixed there - https://github.com/deathkiller/jazz2-native - C++ port of Jazz² Resurrection with a lot of improvements. It's not released yet, it will (probably) be version 1.0.0.

**Comment by coreybruce** [comment] 2022-09-04 16:01
Ohh right so this is the new native version you are talking about, sorry I made a pointless report about a controller issue which probs will be resolved with this new version so I will remove it.
