### ISSUE TITLE
Broken TNT blocks in `xmas3.j2l`

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#117] opened 2022-12-23 15:49 UTC
Game: Christmas Chronicles
Version: 77bffda

TNT doesn't break TNT blocks again. #111

**Comment by deathkiller** [comment] 2022-12-26 16:21
I can't reproduce it. It works good for me. Can you specify it?

**Comment by deathkiller** [comment] 2022-12-26 19:49
These blocks have wrongly assigned weapon index, that's why it can't be destroyed by TNT. But it seems original game doesn't care for some reason and it works there (they probably fixed this bug by creating another bug). I will have to think about it how to fix it.

**Comment by deathkiller** [comment] 2022-12-29 17:48
Fixed in https://github.com/deathkiller/jazz2-native/commit/eefdd6ab7c4a866a53483a4fdd337d95aa238414.

**Closed by deathkiller** 2022-12-29 17:48 UTC
Labels: bug
