### ISSUE TITLE
The game has strange graphical artifacts and lines on Linux and Android

### ISSUE THREAD

**Issue by Poomex** [deathkiller/jazz2#13] opened 2019-04-29 13:55 UTC
The game starts and the music, gameplay and menus work, but the graphics are all illegible - there are artifacts and lines on the screen. I can't even change the graphics settings, because text is impossible to read. 

The exact same thing happens both under Debian 10 and in Android.

I'm not sure what could be the cause of this, so I'm attaching screenshots and the logfile.

> poomex@debian:~/Downloads/Jazz2$ mono Jazz2.exe
Using 'DefaultAssemblyLoader' to load plugins.
Environment Info: 
  Current Directory: /home/poomex/Downloads/Jazz2
  Command Line: /home/poomex/Downloads/Jazz2/Jazz2.exe
  Operating System: Unix 4.19.0.4
  64 Bit OS: True
  64 Bit Process: True
  CLR Version: 4.0.30319.42000
  Processor Count: 16
Currently Loaded Assemblies:
  mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Jazz2, Version=0.5.8.0, Culture=neutral, PublicKeyToken=null
  System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Plugin Base Directories:
  Extensions
Available Assembly Paths:
  Extensions/GL21Backend.core.dll
  Extensions/OpenALSoft.x64.dll
  Extensions/OpenALSoft.x86.dll
  Extensions/OpenTKBackend.core.dll
Assembly loaded: GL21Backend, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly loaded: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly loaded: OpenTKBackend, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading auxiliary libraries...
Assembly loaded: OpenTK, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null
Initializing OpenTK...
Platform Backend: Default
EnableHighResolution: True
Active graphics backend: OpenGL 2.1
Assembly loaded: System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Available display devices:
First : 1920x1080 at  60 Hz, 32 bpp, pos [   0,   0] (Primary)
Available audio devices:
  Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo (Default)
  Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI)
Current device: OpenAL Soft
  OpenAL Version: 1.1 ALSOFT 1.19.1
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Effects: True
Initializing core plugins...
Detected new Gamepad Input: "Gamepad 0" (05000000-4c05-0000-c405-000000810000 | PS4 Controller) at index 0
Detected new Joystick Input: "Joystick 0" (05000000-4c05-0000-c405-000000810000 | Joystick) at index 0
Capabilities: 6 axes, 13 buttons, 1 hats
DualityApp initialized
Debug Mode: False
Command line arguments: 
Window Specification: 
  Buffers: 2
  Samples: 0
  ColorFormat: 24 (8880)
  AccumFormat: 0 (0000)
  Depth: 24
  Stencil: 0
  VSync: On
  SwapInterval: 1
OpenGL Version: 4.5 (Compatibility Profile) Mesa 18.3.4
  Vendor: X.Org
  Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-4-amd64, LLVM 7.0.1)
  Shader Version: 4.50
Can't load animation "MenuDifficultyLori" from metadata "UI/MainMenu": File "Animations\UI\character_art_difficulty_lori.png.res" was not found in CompressedContent
Assembly loaded: System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Assembly loaded: System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Assembly loaded: Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
![Screenshot from 2019-04-29 15-55-02](https://user-images.githubusercontent.com/21321389/56900889-35feae80-6a97-11e9-845f-60c813fe407b.png)
![Screenshot from 2019-04-29 15-55-14](https://user-images.githubusercontent.com/21321389/56900890-36974500-6a97-11e9-9263-8a9f1099b50a.png)

**Comment by xdub** [comment] 2019-04-29 15:43
I have the same problem on Ubuntu 18.04. I reported it on Discord. Interestingly, in Linux installed on VMware, it doesn't do that, but on physical hardware it does. (Sorry - Google translator :-D)

**Comment by deathkiller** [comment] 2019-04-29 16:48
Sorry, but I've already found the cause, it will be fixed soon.

**Comment by deathkiller** [comment] 2019-04-29 20:17
Fixed in v0.5.8.1. Let me know if it works.

**Closed** 2019-04-30 06:11 UTC

**Comment by Poomex** [comment] 2019-04-30 06:56
I confirm it works now, thanks!
