### ISSUE TITLE
Jazz² Resurrection v1.2.0 crashes on Samsung Galaxy S7 Android 8

### ISSUE THREAD

**Issue by gobalius** [deathkiller/jazz2#116] opened 2022-12-04 08:54 UTC
I can not get the game to run.
I followed the instructions exactly:

    Download the game
    Copy contents of original Jazz Jackrabbit 2 directory to ‹Storage›/­Android/­data/­jazz2.­resurrection/­files/­Source/­
    Install Jazz2.­apk or Jazz2_­x86-64.­apk on the device
    Run the newly installed application

See attached Jazz2.log
[Jazz2.log](https://github.com/deathkiller/jazz2/files/10148129/Jazz2.log)

**Comment by deathkiller** [comment] 2022-12-04 10:34
Hi, try to download `Jazz2_Android_DEBUG_ARM` version from https://github.com/deathkiller/jazz2-native/actions/runs/3601622456 and let me know.

**Comment by gobalius** [comment] 2022-12-04 13:07
However, on another Android phone - Samsung Galaxy S21 FE 5G it is not working.
[Jazz2.log](https://github.com/deathkiller/jazz2/files/10148546/Jazz2.log)
It can't see the files I've put in the folder /storage/emulated/0/Android/data/jazz2.resurrection/files/Source/
Even though it does write the log file in the folder /storage/emulated/0/Android/data/jazz2.resurrection/files/

**Comment by deathkiller** [comment] 2022-12-04 18:03
It's Samsung Galaxy S7 with Mali GPU, right? It seems there is some problem only with Mali GPUs.
How many FPS do you have with this version?

**Comment by gobalius** [comment] 2022-12-04 19:04
Yes, it has Mali-T880 MP12. With this version I get perfect 60 fps, also in the dark areas.

**Comment by deathkiller** [comment] 2022-12-05 12:24
Ok, can you download the latest experimental build `Jazz2_Android_ARM` (the non-DEBUG version), try it again and send me log file, please?
https://github.com/deathkiller/jazz2-native/actions/workflows/android.yml

**Comment by gobalius** [comment] 2022-12-05 18:56
The DEBUG version on the other hand is working:
[Jazz2.log](https://github.com/deathkiller/jazz2/files/10157115/Jazz2.log)

**Comment by deathkiller** [comment] 2022-12-05 22:50
thanks, I think I know the cause now, it will hopefully be fixed in the next few days

**Comment by deathkiller** [comment] 2023-02-16 13:57
This should be fixed now in the latest experimental build (the non-DEBUG version).

**Closed by deathkiller** 2023-02-16 13:57 UTC
Labels: bug
