### ISSUE TITLE
After being teleported by the money rabbit to bonus location, all remaining coins should be switched to gems

### ISSUE THREAD

**Issue by Scorcerer** [deathkiller/jazz2#123] opened 2023-01-25 00:34 UTC
Hi!
As in the topic, I believe silver coins should be red gems and gold coins should be green ones.

**Comment by deathkiller** [comment] 2023-01-25 08:29
This should work already, it doesn't? Also, all gem types were merged into single count and all coin types too.
https://github.com/deathkiller/jazz2-native/blob/master/Sources/Jazz2/Actors/Player.cpp#L1153-L1158

**Comment by Scorcerer** [comment] 2023-01-25 20:34
No, i encountered it multiple times while playing the latest version...

**Comment by deathkiller** [comment] 2023-01-26 18:26
I can't reproduce it. It works, e.g. I got 45 coins, bonus warp requires 20 and the rest will be converted to 25 gems.

**Closed** 2023-02-04 17:50 UTC
