### ISSUE TITLE
[Feature request] Local play using Wifi & Bluetooth

### ISSUE THREAD

**Issue by Alyaqdhans** [deathkiller/jazz2#144] opened 2024-10-29 13:04 UTC
The original game had a local online party mode (also split screen), is it possible to implement local play using wifi or bluetooth?
![image](https://github.com/user-attachments/assets/f268b404-e23d-4c7d-950e-e208ed44d2f1)
![image](https://github.com/user-attachments/assets/f72f02f1-dabf-4076-acdc-c38a735525f5)

There are multiple examples that have this implementation (android):
- [Pou](https://play.google.com/store/apps/details?id=me.pou.app&hl=en)
![image](https://github.com/user-attachments/assets/f9a1c8a4-a5da-4d0c-a6d8-971bc8f6ef5c)
- [BombSquad](https://play.google.com/store/apps/details?id=net.froemling.bombsquad&hl=en)
![image](https://github.com/user-attachments/assets/2ccef7d7-c357-4658-a2b3-63b32535d63e)
- [Terraria](https://play.google.com/store/apps/details?id=com.and.games505.TerrariaPaid&hl=en) (only local wifi)
![image](https://github.com/user-attachments/assets/63721852-befa-4af7-a9d6-356c1a8651e8)

**Comment by deathkiller** [comment] 2024-10-29 19:41
Duplicate of https://github.com/deathkiller/jazz2-native/issues/39.

It's work in progress already, not yet publicly released.

**Closed by deathkiller** 2024-10-29 19:41 UTC
